#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWine.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLiBanRuou")]
	public partial class dbQLBanRuouDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertCapDo(CapDo instance);
    partial void UpdateCapDo(CapDo instance);
    partial void DeleteCapDo(CapDo instance);
    partial void InsertCTDatHang(CTDatHang instance);
    partial void UpdateCTDatHang(CTDatHang instance);
    partial void DeleteCTDatHang(CTDatHang instance);
    partial void InsertDonDatHang(DonDatHang instance);
    partial void UpdateDonDatHang(DonDatHang instance);
    partial void DeleteDonDatHang(DonDatHang instance);
    partial void InsertHuongLieu(HuongLieu instance);
    partial void UpdateHuongLieu(HuongLieu instance);
    partial void DeleteHuongLieu(HuongLieu instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiRuou(LoaiRuou instance);
    partial void UpdateLoaiRuou(LoaiRuou instance);
    partial void DeleteLoaiRuou(LoaiRuou instance);
    partial void InsertNhaSanXuat(NhaSanXuat instance);
    partial void UpdateNhaSanXuat(NhaSanXuat instance);
    partial void DeleteNhaSanXuat(NhaSanXuat instance);
    partial void InsertRuou(Ruou instance);
    partial void UpdateRuou(Ruou instance);
    partial void DeleteRuou(Ruou instance);
    partial void InsertThanhToan(ThanhToan instance);
    partial void UpdateThanhToan(ThanhToan instance);
    partial void DeleteThanhToan(ThanhToan instance);
    #endregion
		
		public dbQLBanRuouDataContext() : 
				base(global::WebWine.Properties.Settings.Default.QuanLiBanRuouConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLBanRuouDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLBanRuouDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLBanRuouDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLBanRuouDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<CapDo> CapDos
		{
			get
			{
				return this.GetTable<CapDo>();
			}
		}
		
		public System.Data.Linq.Table<CTDatHang> CTDatHangs
		{
			get
			{
				return this.GetTable<CTDatHang>();
			}
		}
		
		public System.Data.Linq.Table<DonDatHang> DonDatHangs
		{
			get
			{
				return this.GetTable<DonDatHang>();
			}
		}
		
		public System.Data.Linq.Table<HuongLieu> HuongLieus
		{
			get
			{
				return this.GetTable<HuongLieu>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiRuou> LoaiRuous
		{
			get
			{
				return this.GetTable<LoaiRuou>();
			}
		}
		
		public System.Data.Linq.Table<NhaSanXuat> NhaSanXuats
		{
			get
			{
				return this.GetTable<NhaSanXuat>();
			}
		}
		
		public System.Data.Linq.Table<Ruou> Ruous
		{
			get
			{
				return this.GetTable<Ruou>();
			}
		}
		
		public System.Data.Linq.Table<ThanhToan> ThanhToans
		{
			get
			{
				return this.GetTable<ThanhToan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserAdmin;
		
		private string _PassAdmin;
		
		private string _Hoten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserAdminChanging(string value);
    partial void OnUserAdminChanged();
    partial void OnPassAdminChanging(string value);
    partial void OnPassAdminChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAdmin", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserAdmin
		{
			get
			{
				return this._UserAdmin;
			}
			set
			{
				if ((this._UserAdmin != value))
				{
					this.OnUserAdminChanging(value);
					this.SendPropertyChanging();
					this._UserAdmin = value;
					this.SendPropertyChanged("UserAdmin");
					this.OnUserAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassAdmin", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PassAdmin
		{
			get
			{
				return this._PassAdmin;
			}
			set
			{
				if ((this._PassAdmin != value))
				{
					this.OnPassAdminChanging(value);
					this.SendPropertyChanging();
					this._PassAdmin = value;
					this.SendPropertyChanged("PassAdmin");
					this.OnPassAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CapDo")]
	public partial class CapDo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCD;
		
		private string _Capdo1;
		
		private EntitySet<Ruou> _Ruous;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCDChanging(int value);
    partial void OnMaCDChanged();
    partial void OnCapdo1Changing(string value);
    partial void OnCapdo1Changed();
    #endregion
		
		public CapDo()
		{
			this._Ruous = new EntitySet<Ruou>(new Action<Ruou>(this.attach_Ruous), new Action<Ruou>(this.detach_Ruous));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCD
		{
			get
			{
				return this._MaCD;
			}
			set
			{
				if ((this._MaCD != value))
				{
					this.OnMaCDChanging(value);
					this.SendPropertyChanging();
					this._MaCD = value;
					this.SendPropertyChanged("MaCD");
					this.OnMaCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Capdo", Storage="_Capdo1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Capdo1
		{
			get
			{
				return this._Capdo1;
			}
			set
			{
				if ((this._Capdo1 != value))
				{
					this.OnCapdo1Changing(value);
					this.SendPropertyChanging();
					this._Capdo1 = value;
					this.SendPropertyChanged("Capdo1");
					this.OnCapdo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapDo_Ruou", Storage="_Ruous", ThisKey="MaCD", OtherKey="MaCD")]
		public EntitySet<Ruou> Ruous
		{
			get
			{
				return this._Ruous;
			}
			set
			{
				this._Ruous.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ruous(Ruou entity)
		{
			this.SendPropertyChanging();
			entity.CapDo = this;
		}
		
		private void detach_Ruous(Ruou entity)
		{
			this.SendPropertyChanging();
			entity.CapDo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTDatHang")]
	public partial class CTDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDH;
		
		private System.Nullable<int> _MaSP;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<decimal> _Dongia;
		
		private EntityRef<DonDatHang> _DonDatHang;
		
		private EntityRef<Ruou> _Ruou;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDHChanging(int value);
    partial void OnMaDHChanged();
    partial void OnMaSPChanging(System.Nullable<int> value);
    partial void OnMaSPChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnDongiaChanging(System.Nullable<decimal> value);
    partial void OnDongiaChanged();
    #endregion
		
		public CTDatHang()
		{
			this._DonDatHang = default(EntityRef<DonDatHang>);
			this._Ruou = default(EntityRef<Ruou>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDH
		{
			get
			{
				return this._MaDH;
			}
			set
			{
				if ((this._MaDH != value))
				{
					if (this._DonDatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDHChanging(value);
					this.SendPropertyChanging();
					this._MaDH = value;
					this.SendPropertyChanged("MaDH");
					this.OnMaDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Int")]
		public System.Nullable<int> MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._Ruou.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHang_CTDatHang", Storage="_DonDatHang", ThisKey="MaDH", OtherKey="MaDH", IsForeignKey=true)]
		public DonDatHang DonDatHang
		{
			get
			{
				return this._DonDatHang.Entity;
			}
			set
			{
				DonDatHang previousValue = this._DonDatHang.Entity;
				if (((previousValue != value) 
							|| (this._DonDatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonDatHang.Entity = null;
						previousValue.CTDatHang = null;
					}
					this._DonDatHang.Entity = value;
					if ((value != null))
					{
						value.CTDatHang = this;
						this._MaDH = value.MaDH;
					}
					else
					{
						this._MaDH = default(int);
					}
					this.SendPropertyChanged("DonDatHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruou_CTDatHang", Storage="_Ruou", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public Ruou Ruou
		{
			get
			{
				return this._Ruou.Entity;
			}
			set
			{
				Ruou previousValue = this._Ruou.Entity;
				if (((previousValue != value) 
							|| (this._Ruou.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ruou.Entity = null;
						previousValue.CTDatHangs.Remove(this);
					}
					this._Ruou.Entity = value;
					if ((value != null))
					{
						value.CTDatHangs.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(Nullable<int>);
					}
					this.SendPropertyChanged("Ruou");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonDatHang")]
	public partial class DonDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDH;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<System.DateTime> _Ngaydat;
		
		private string _Diachigiao;
		
		private System.Nullable<decimal> _Tongtien;
		
		private System.Nullable<int> _MaTT;
		
		private EntityRef<CTDatHang> _CTDatHang;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<ThanhToan> _ThanhToan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDHChanging(int value);
    partial void OnMaDHChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnNgaydatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydatChanged();
    partial void OnDiachigiaoChanging(string value);
    partial void OnDiachigiaoChanged();
    partial void OnTongtienChanging(System.Nullable<decimal> value);
    partial void OnTongtienChanged();
    partial void OnMaTTChanging(System.Nullable<int> value);
    partial void OnMaTTChanged();
    #endregion
		
		public DonDatHang()
		{
			this._CTDatHang = default(EntityRef<CTDatHang>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._ThanhToan = default(EntityRef<ThanhToan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDH
		{
			get
			{
				return this._MaDH;
			}
			set
			{
				if ((this._MaDH != value))
				{
					this.OnMaDHChanging(value);
					this.SendPropertyChanging();
					this._MaDH = value;
					this.SendPropertyChanged("MaDH");
					this.OnMaDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydat", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydat
		{
			get
			{
				return this._Ngaydat;
			}
			set
			{
				if ((this._Ngaydat != value))
				{
					this.OnNgaydatChanging(value);
					this.SendPropertyChanging();
					this._Ngaydat = value;
					this.SendPropertyChanged("Ngaydat");
					this.OnNgaydatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachigiao", DbType="NVarChar(MAX)")]
		public string Diachigiao
		{
			get
			{
				return this._Diachigiao;
			}
			set
			{
				if ((this._Diachigiao != value))
				{
					this.OnDiachigiaoChanging(value);
					this.SendPropertyChanging();
					this._Diachigiao = value;
					this.SendPropertyChanged("Diachigiao");
					this.OnDiachigiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tongtien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Tongtien
		{
			get
			{
				return this._Tongtien;
			}
			set
			{
				if ((this._Tongtien != value))
				{
					this.OnTongtienChanging(value);
					this.SendPropertyChanging();
					this._Tongtien = value;
					this.SendPropertyChanged("Tongtien");
					this.OnTongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="Int")]
		public System.Nullable<int> MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					if (this._ThanhToan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHang_CTDatHang", Storage="_CTDatHang", ThisKey="MaDH", OtherKey="MaDH", IsUnique=true, IsForeignKey=false)]
		public CTDatHang CTDatHang
		{
			get
			{
				return this._CTDatHang.Entity;
			}
			set
			{
				CTDatHang previousValue = this._CTDatHang.Entity;
				if (((previousValue != value) 
							|| (this._CTDatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CTDatHang.Entity = null;
						previousValue.DonDatHang = null;
					}
					this._CTDatHang.Entity = value;
					if ((value != null))
					{
						value.DonDatHang = this;
					}
					this.SendPropertyChanged("CTDatHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatHang", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DonDatHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DonDatHangs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhToan_DonDatHang", Storage="_ThanhToan", ThisKey="MaTT", OtherKey="MaTT", IsForeignKey=true)]
		public ThanhToan ThanhToan
		{
			get
			{
				return this._ThanhToan.Entity;
			}
			set
			{
				ThanhToan previousValue = this._ThanhToan.Entity;
				if (((previousValue != value) 
							|| (this._ThanhToan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhToan.Entity = null;
						previousValue.DonDatHangs.Remove(this);
					}
					this._ThanhToan.Entity = value;
					if ((value != null))
					{
						value.DonDatHangs.Add(this);
						this._MaTT = value.MaTT;
					}
					else
					{
						this._MaTT = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThanhToan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HuongLieu")]
	public partial class HuongLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHL;
		
		private string _TenHL;
		
		private EntitySet<Ruou> _Ruous;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHLChanging(int value);
    partial void OnMaHLChanged();
    partial void OnTenHLChanging(string value);
    partial void OnTenHLChanged();
    #endregion
		
		public HuongLieu()
		{
			this._Ruous = new EntitySet<Ruou>(new Action<Ruou>(this.attach_Ruous), new Action<Ruou>(this.detach_Ruous));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHL
		{
			get
			{
				return this._MaHL;
			}
			set
			{
				if ((this._MaHL != value))
				{
					this.OnMaHLChanging(value);
					this.SendPropertyChanging();
					this._MaHL = value;
					this.SendPropertyChanged("MaHL");
					this.OnMaHLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenHL
		{
			get
			{
				return this._TenHL;
			}
			set
			{
				if ((this._TenHL != value))
				{
					this.OnTenHLChanging(value);
					this.SendPropertyChanging();
					this._TenHL = value;
					this.SendPropertyChanged("TenHL");
					this.OnTenHLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HuongLieu_Ruou", Storage="_Ruous", ThisKey="MaHL", OtherKey="MaHL")]
		public EntitySet<Ruou> Ruous
		{
			get
			{
				return this._Ruous;
			}
			set
			{
				this._Ruous.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ruous(Ruou entity)
		{
			this.SendPropertyChanging();
			entity.HuongLieu = this;
		}
		
		private void detach_Ruous(Ruou entity)
		{
			this.SendPropertyChanging();
			entity.HuongLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _TenKH;
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _Gioitinh;
		
		private string _EmailKH;
		
		private string _DiachiKH;
		
		private string _DienthoaiKH;
		
		private EntitySet<DonDatHang> _DonDatHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnEmailKHChanging(string value);
    partial void OnEmailKHChanged();
    partial void OnDiachiKHChanging(string value);
    partial void OnDiachiKHChanged();
    partial void OnDienthoaiKHChanging(string value);
    partial void OnDienthoaiKHChanged();
    #endregion
		
		public KhachHang()
		{
			this._DonDatHangs = new EntitySet<DonDatHang>(new Action<DonDatHang>(this.attach_DonDatHangs), new Action<DonDatHang>(this.detach_DonDatHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="VarChar(50)")]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="VarChar(50)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(5)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailKH", DbType="VarChar(50)")]
		public string EmailKH
		{
			get
			{
				return this._EmailKH;
			}
			set
			{
				if ((this._EmailKH != value))
				{
					this.OnEmailKHChanging(value);
					this.SendPropertyChanging();
					this._EmailKH = value;
					this.SendPropertyChanged("EmailKH");
					this.OnEmailKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiachiKH", DbType="NVarChar(200)")]
		public string DiachiKH
		{
			get
			{
				return this._DiachiKH;
			}
			set
			{
				if ((this._DiachiKH != value))
				{
					this.OnDiachiKHChanging(value);
					this.SendPropertyChanging();
					this._DiachiKH = value;
					this.SendPropertyChanged("DiachiKH");
					this.OnDiachiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienthoaiKH", DbType="VarChar(11)")]
		public string DienthoaiKH
		{
			get
			{
				return this._DienthoaiKH;
			}
			set
			{
				if ((this._DienthoaiKH != value))
				{
					this.OnDienthoaiKHChanging(value);
					this.SendPropertyChanging();
					this._DienthoaiKH = value;
					this.SendPropertyChanged("DienthoaiKH");
					this.OnDienthoaiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatHang", Storage="_DonDatHangs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DonDatHang> DonDatHangs
		{
			get
			{
				return this._DonDatHangs;
			}
			set
			{
				this._DonDatHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiRuou")]
	public partial class LoaiRuou : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoai;
		
		private string _LoaiRuou1;
		
		private EntitySet<Ruou> _Ruous;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(int value);
    partial void OnMaLoaiChanged();
    partial void OnLoaiRuou1Changing(string value);
    partial void OnLoaiRuou1Changed();
    #endregion
		
		public LoaiRuou()
		{
			this._Ruous = new EntitySet<Ruou>(new Action<Ruou>(this.attach_Ruous), new Action<Ruou>(this.detach_Ruous));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="LoaiRuou", Storage="_LoaiRuou1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiRuou1
		{
			get
			{
				return this._LoaiRuou1;
			}
			set
			{
				if ((this._LoaiRuou1 != value))
				{
					this.OnLoaiRuou1Changing(value);
					this.SendPropertyChanging();
					this._LoaiRuou1 = value;
					this.SendPropertyChanged("LoaiRuou1");
					this.OnLoaiRuou1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiRuou_Ruou", Storage="_Ruous", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<Ruou> Ruous
		{
			get
			{
				return this._Ruous;
			}
			set
			{
				this._Ruous.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ruous(Ruou entity)
		{
			this.SendPropertyChanging();
			entity.LoaiRuou = this;
		}
		
		private void detach_Ruous(Ruou entity)
		{
			this.SendPropertyChanging();
			entity.LoaiRuou = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaSanXuat")]
	public partial class NhaSanXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNSX;
		
		private string _TenNSX;
		
		private string _DiachiNSX;
		
		private string _DienthoaiNSX;
		
		private string _WebsiteNSX;
		
		private EntitySet<Ruou> _Ruous;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNSXChanging(int value);
    partial void OnMaNSXChanged();
    partial void OnTenNSXChanging(string value);
    partial void OnTenNSXChanged();
    partial void OnDiachiNSXChanging(string value);
    partial void OnDiachiNSXChanged();
    partial void OnDienthoaiNSXChanging(string value);
    partial void OnDienthoaiNSXChanged();
    partial void OnWebsiteNSXChanging(string value);
    partial void OnWebsiteNSXChanged();
    #endregion
		
		public NhaSanXuat()
		{
			this._Ruous = new EntitySet<Ruou>(new Action<Ruou>(this.attach_Ruous), new Action<Ruou>(this.detach_Ruous));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSX", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNSX
		{
			get
			{
				return this._MaNSX;
			}
			set
			{
				if ((this._MaNSX != value))
				{
					this.OnMaNSXChanging(value);
					this.SendPropertyChanging();
					this._MaNSX = value;
					this.SendPropertyChanged("MaNSX");
					this.OnMaNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNSX", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNSX
		{
			get
			{
				return this._TenNSX;
			}
			set
			{
				if ((this._TenNSX != value))
				{
					this.OnTenNSXChanging(value);
					this.SendPropertyChanging();
					this._TenNSX = value;
					this.SendPropertyChanged("TenNSX");
					this.OnTenNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiachiNSX", DbType="NVarChar(200)")]
		public string DiachiNSX
		{
			get
			{
				return this._DiachiNSX;
			}
			set
			{
				if ((this._DiachiNSX != value))
				{
					this.OnDiachiNSXChanging(value);
					this.SendPropertyChanging();
					this._DiachiNSX = value;
					this.SendPropertyChanged("DiachiNSX");
					this.OnDiachiNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienthoaiNSX", DbType="VarChar(11)")]
		public string DienthoaiNSX
		{
			get
			{
				return this._DienthoaiNSX;
			}
			set
			{
				if ((this._DienthoaiNSX != value))
				{
					this.OnDienthoaiNSXChanging(value);
					this.SendPropertyChanging();
					this._DienthoaiNSX = value;
					this.SendPropertyChanged("DienthoaiNSX");
					this.OnDienthoaiNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebsiteNSX", DbType="VarChar(50)")]
		public string WebsiteNSX
		{
			get
			{
				return this._WebsiteNSX;
			}
			set
			{
				if ((this._WebsiteNSX != value))
				{
					this.OnWebsiteNSXChanging(value);
					this.SendPropertyChanging();
					this._WebsiteNSX = value;
					this.SendPropertyChanged("WebsiteNSX");
					this.OnWebsiteNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaSanXuat_Ruou", Storage="_Ruous", ThisKey="MaNSX", OtherKey="MaNSX")]
		public EntitySet<Ruou> Ruous
		{
			get
			{
				return this._Ruous;
			}
			set
			{
				this._Ruous.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ruous(Ruou entity)
		{
			this.SendPropertyChanging();
			entity.NhaSanXuat = this;
		}
		
		private void detach_Ruous(Ruou entity)
		{
			this.SendPropertyChanging();
			entity.NhaSanXuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ruou")]
	public partial class Ruou : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSP;
		
		private System.Nullable<int> _MaLoai;
		
		private string _Ruou1;
		
		private string _Anhbia;
		
		private string _Anh1;
		
		private string _Anh2;
		
		private string _Mota;
		
		private System.Nullable<int> _MaHL;
		
		private System.Nullable<int> _NamSX;
		
		private System.Nullable<int> _MaNSX;
		
		private System.Nullable<int> _MaCD;
		
		private System.Nullable<int> _Nongdo;
		
		private System.Nullable<int> _Dungtich;
		
		private System.Nullable<System.DateTime> _Ngaycapnhat;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<decimal> _Giaban;
		
		private EntitySet<CTDatHang> _CTDatHangs;
		
		private EntityRef<CapDo> _CapDo;
		
		private EntityRef<HuongLieu> _HuongLieu;
		
		private EntityRef<LoaiRuou> _LoaiRuou;
		
		private EntityRef<NhaSanXuat> _NhaSanXuat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(int value);
    partial void OnMaSPChanged();
    partial void OnMaLoaiChanging(System.Nullable<int> value);
    partial void OnMaLoaiChanged();
    partial void OnRuou1Changing(string value);
    partial void OnRuou1Changed();
    partial void OnAnhbiaChanging(string value);
    partial void OnAnhbiaChanged();
    partial void OnAnh1Changing(string value);
    partial void OnAnh1Changed();
    partial void OnAnh2Changing(string value);
    partial void OnAnh2Changed();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnMaHLChanging(System.Nullable<int> value);
    partial void OnMaHLChanged();
    partial void OnNamSXChanging(System.Nullable<int> value);
    partial void OnNamSXChanged();
    partial void OnMaNSXChanging(System.Nullable<int> value);
    partial void OnMaNSXChanged();
    partial void OnMaCDChanging(System.Nullable<int> value);
    partial void OnMaCDChanged();
    partial void OnNongdoChanging(System.Nullable<int> value);
    partial void OnNongdoChanged();
    partial void OnDungtichChanging(System.Nullable<int> value);
    partial void OnDungtichChanged();
    partial void OnNgaycapnhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaycapnhatChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnGiabanChanging(System.Nullable<decimal> value);
    partial void OnGiabanChanged();
    #endregion
		
		public Ruou()
		{
			this._CTDatHangs = new EntitySet<CTDatHang>(new Action<CTDatHang>(this.attach_CTDatHangs), new Action<CTDatHang>(this.detach_CTDatHangs));
			this._CapDo = default(EntityRef<CapDo>);
			this._HuongLieu = default(EntityRef<HuongLieu>);
			this._LoaiRuou = default(EntityRef<LoaiRuou>);
			this._NhaSanXuat = default(EntityRef<NhaSanXuat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="Int")]
		public System.Nullable<int> MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._LoaiRuou.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ruou", Storage="_Ruou1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ruou1
		{
			get
			{
				return this._Ruou1;
			}
			set
			{
				if ((this._Ruou1 != value))
				{
					this.OnRuou1Changing(value);
					this.SendPropertyChanging();
					this._Ruou1 = value;
					this.SendPropertyChanged("Ruou1");
					this.OnRuou1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anhbia", DbType="VarChar(50)")]
		public string Anhbia
		{
			get
			{
				return this._Anhbia;
			}
			set
			{
				if ((this._Anhbia != value))
				{
					this.OnAnhbiaChanging(value);
					this.SendPropertyChanging();
					this._Anhbia = value;
					this.SendPropertyChanged("Anhbia");
					this.OnAnhbiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh1", DbType="VarChar(50)")]
		public string Anh1
		{
			get
			{
				return this._Anh1;
			}
			set
			{
				if ((this._Anh1 != value))
				{
					this.OnAnh1Changing(value);
					this.SendPropertyChanging();
					this._Anh1 = value;
					this.SendPropertyChanged("Anh1");
					this.OnAnh1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh2", DbType="VarChar(50)")]
		public string Anh2
		{
			get
			{
				return this._Anh2;
			}
			set
			{
				if ((this._Anh2 != value))
				{
					this.OnAnh2Changing(value);
					this.SendPropertyChanging();
					this._Anh2 = value;
					this.SendPropertyChanged("Anh2");
					this.OnAnh2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(MAX)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHL", DbType="Int")]
		public System.Nullable<int> MaHL
		{
			get
			{
				return this._MaHL;
			}
			set
			{
				if ((this._MaHL != value))
				{
					if (this._HuongLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHLChanging(value);
					this.SendPropertyChanging();
					this._MaHL = value;
					this.SendPropertyChanged("MaHL");
					this.OnMaHLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="Int")]
		public System.Nullable<int> NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this.OnNamSXChanging(value);
					this.SendPropertyChanging();
					this._NamSX = value;
					this.SendPropertyChanged("NamSX");
					this.OnNamSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSX", DbType="Int")]
		public System.Nullable<int> MaNSX
		{
			get
			{
				return this._MaNSX;
			}
			set
			{
				if ((this._MaNSX != value))
				{
					if (this._NhaSanXuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNSXChanging(value);
					this.SendPropertyChanging();
					this._MaNSX = value;
					this.SendPropertyChanged("MaNSX");
					this.OnMaNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCD", DbType="Int")]
		public System.Nullable<int> MaCD
		{
			get
			{
				return this._MaCD;
			}
			set
			{
				if ((this._MaCD != value))
				{
					if (this._CapDo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCDChanging(value);
					this.SendPropertyChanging();
					this._MaCD = value;
					this.SendPropertyChanged("MaCD");
					this.OnMaCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nongdo", DbType="Int")]
		public System.Nullable<int> Nongdo
		{
			get
			{
				return this._Nongdo;
			}
			set
			{
				if ((this._Nongdo != value))
				{
					this.OnNongdoChanging(value);
					this.SendPropertyChanging();
					this._Nongdo = value;
					this.SendPropertyChanged("Nongdo");
					this.OnNongdoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dungtich", DbType="Int")]
		public System.Nullable<int> Dungtich
		{
			get
			{
				return this._Dungtich;
			}
			set
			{
				if ((this._Dungtich != value))
				{
					this.OnDungtichChanging(value);
					this.SendPropertyChanging();
					this._Dungtich = value;
					this.SendPropertyChanged("Dungtich");
					this.OnDungtichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaycapnhat
		{
			get
			{
				return this._Ngaycapnhat;
			}
			set
			{
				if ((this._Ngaycapnhat != value))
				{
					this.OnNgaycapnhatChanging(value);
					this.SendPropertyChanging();
					this._Ngaycapnhat = value;
					this.SendPropertyChanged("Ngaycapnhat");
					this.OnNgaycapnhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giaban", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Giaban
		{
			get
			{
				return this._Giaban;
			}
			set
			{
				if ((this._Giaban != value))
				{
					this.OnGiabanChanging(value);
					this.SendPropertyChanging();
					this._Giaban = value;
					this.SendPropertyChanged("Giaban");
					this.OnGiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruou_CTDatHang", Storage="_CTDatHangs", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<CTDatHang> CTDatHangs
		{
			get
			{
				return this._CTDatHangs;
			}
			set
			{
				this._CTDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapDo_Ruou", Storage="_CapDo", ThisKey="MaCD", OtherKey="MaCD", IsForeignKey=true)]
		public CapDo CapDo
		{
			get
			{
				return this._CapDo.Entity;
			}
			set
			{
				CapDo previousValue = this._CapDo.Entity;
				if (((previousValue != value) 
							|| (this._CapDo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CapDo.Entity = null;
						previousValue.Ruous.Remove(this);
					}
					this._CapDo.Entity = value;
					if ((value != null))
					{
						value.Ruous.Add(this);
						this._MaCD = value.MaCD;
					}
					else
					{
						this._MaCD = default(Nullable<int>);
					}
					this.SendPropertyChanged("CapDo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HuongLieu_Ruou", Storage="_HuongLieu", ThisKey="MaHL", OtherKey="MaHL", IsForeignKey=true)]
		public HuongLieu HuongLieu
		{
			get
			{
				return this._HuongLieu.Entity;
			}
			set
			{
				HuongLieu previousValue = this._HuongLieu.Entity;
				if (((previousValue != value) 
							|| (this._HuongLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HuongLieu.Entity = null;
						previousValue.Ruous.Remove(this);
					}
					this._HuongLieu.Entity = value;
					if ((value != null))
					{
						value.Ruous.Add(this);
						this._MaHL = value.MaHL;
					}
					else
					{
						this._MaHL = default(Nullable<int>);
					}
					this.SendPropertyChanged("HuongLieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiRuou_Ruou", Storage="_LoaiRuou", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true)]
		public LoaiRuou LoaiRuou
		{
			get
			{
				return this._LoaiRuou.Entity;
			}
			set
			{
				LoaiRuou previousValue = this._LoaiRuou.Entity;
				if (((previousValue != value) 
							|| (this._LoaiRuou.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiRuou.Entity = null;
						previousValue.Ruous.Remove(this);
					}
					this._LoaiRuou.Entity = value;
					if ((value != null))
					{
						value.Ruous.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiRuou");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaSanXuat_Ruou", Storage="_NhaSanXuat", ThisKey="MaNSX", OtherKey="MaNSX", IsForeignKey=true)]
		public NhaSanXuat NhaSanXuat
		{
			get
			{
				return this._NhaSanXuat.Entity;
			}
			set
			{
				NhaSanXuat previousValue = this._NhaSanXuat.Entity;
				if (((previousValue != value) 
							|| (this._NhaSanXuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaSanXuat.Entity = null;
						previousValue.Ruous.Remove(this);
					}
					this._NhaSanXuat.Entity = value;
					if ((value != null))
					{
						value.Ruous.Add(this);
						this._MaNSX = value.MaNSX;
					}
					else
					{
						this._MaNSX = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhaSanXuat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTDatHangs(CTDatHang entity)
		{
			this.SendPropertyChanging();
			entity.Ruou = this;
		}
		
		private void detach_CTDatHangs(CTDatHang entity)
		{
			this.SendPropertyChanging();
			entity.Ruou = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhToan")]
	public partial class ThanhToan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTT;
		
		private string _Thanhtoan1;
		
		private EntitySet<DonDatHang> _DonDatHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTChanging(int value);
    partial void OnMaTTChanged();
    partial void OnThanhtoan1Changing(string value);
    partial void OnThanhtoan1Changed();
    #endregion
		
		public ThanhToan()
		{
			this._DonDatHangs = new EntitySet<DonDatHang>(new Action<DonDatHang>(this.attach_DonDatHangs), new Action<DonDatHang>(this.detach_DonDatHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Thanhtoan", Storage="_Thanhtoan1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Thanhtoan1
		{
			get
			{
				return this._Thanhtoan1;
			}
			set
			{
				if ((this._Thanhtoan1 != value))
				{
					this.OnThanhtoan1Changing(value);
					this.SendPropertyChanging();
					this._Thanhtoan1 = value;
					this.SendPropertyChanged("Thanhtoan1");
					this.OnThanhtoan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhToan_DonDatHang", Storage="_DonDatHangs", ThisKey="MaTT", OtherKey="MaTT")]
		public EntitySet<DonDatHang> DonDatHangs
		{
			get
			{
				return this._DonDatHangs;
			}
			set
			{
				this._DonDatHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.ThanhToan = this;
		}
		
		private void detach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.ThanhToan = null;
		}
	}
}
#pragma warning restore 1591
